on:
  push:
    branches: master
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: mvn --batch-mode verify
    - uses: actions/upload-artifact@v4
      with:
        path: target/icalendar-validator-*-jar-with-dependencies.jar
